### ISSUE TITLE
Ghost NPCs can cast annihilate undead

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#104]
so yeah, reported this a couple years ago, figure i'll rereport it....

this is the top quested spell for necromancer.  A lich does not get this spell, and a necro that has it, loses it when they become a lich.

Any ghost, can cast this spell upon command, whether or not the master has the spell quested, or is a lich

a lich, can thusly, use their ghosts to cast annihilate undead, while they cast their top lvl spell, siphon undead......i stop'd playing necro when i discovered that a lich gets free access to the spell i spent mucho time trying to get quested!

**Comment by Nyyrazzilyss** [comment]
Related, ghosts can also cast vampiric curse - not that it appears to work anyways

(edit) - I read the helpfile for vampiric curse :( Only the living can cast it successfully = Removed!

**Comment by Inames** [comment]
Pretty sure that tidbit in the helpfile about living necromancers just implies that lich's don't get the spell. I've landed vamp curse using my wraiths/ghosts, the spell just has like a .5% success rate which is why it doesn't get used by people playing necromancers either. Vamp curse needs to be looked at. Though I haven't tried to use it with powers because I don't have a necromancer with it quested.
