### ISSUE TITLE
help sorcerer mentions two other help pages which I can't pull up

### ISSUE THREAD

**Issue by byzanthia** [torilmud/issues#1054]
help sorcerer
```
SORCERER

Sorcerers are innate spell casters who have been born with access
to arcane power. The spells at their command are channeled from
their innate affinity and do not come from a deity, or a spell book.
Sorcerers specialize in offensive magic, and their melee capabilities
are very limited. Access to metamagic and other powerful incantations
more than make up for this shortcoming.

Sorcerers may choose a subclass by using the "class" command at an
inn.

Subclasses:             Draconic, Wild Magic

Allowable races:        Human, Drow, Elf, Halfling, Gnome, Yuan-Ti,
                        Half-Orc.

Minimum stats:          STR: 50   DEX: 40   AGI:  0   CON: 50
                        POW: 0   INT: 90   WIS: 0   CHA:  0

                        For information on stats, please type:
                        "help class stats"

Sorcerer skills:         For an up-to-date listing of the available
                        invoker skills, spells, and their levels,
                        type: "help skill_sorcerer"

Equipment usage:        Sorcerers fall into the Magic-User
                        classification of item restriction.  This
                        means they have the smallest range of weapons
                        that they can wield and a very small range of
                        armor from which to choose.  They have almost
                        no restrictions on what miscellaneous magical
                        items they can use (wands, staffs, etc.)

Sorcerers can improve their skills by using the "practice" command in
their guild.


See also:  MAGIC-USER, PRACTICE, GUILD, SKILL_SORCERER, SKILLS,
           SPELLCAST, SPECIALIZE, MAGIC, SUBCLASS, DRACONIC, "WILD MAGIC"

```

 
However, when I try to find out more about  draconic and wild magic, I just get two powers:

```
help wild magic;;help draconic


Name             : Wild Magic Storm  
Type             : Enchantment              
Target           : Self

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Add combo cost trigger effect for 30 seconds       
Self Effect      : --> Allow a free use of Chaos Storm                

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
When affected by this, the Sorcerer may cast a free Chaos Storm.

Name             : Draconic Majesty [dm]
Type             : Spell                    
Prepare          : At will                  
Target           : Self
Recharge         : 1 minute 
Restrictions     : Standing, Can Speak

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Add inflict spell damage trigger effect for 20 seconds  
Self Effect      : --> Modify inflict spell damage by +20% for 20 seconds  

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
The primal power of draconic might infuses the caster upon completing this spell.
While infused with this power, the caster's innate link to sorcerous magic intensifies,
causing bonus damage to be applied to every spell cast while under the duration.

```

Was that intended? I was hoping to read more about the subclasses, not specific powers.

**Comment by marthammor** [comment]
For wild magic, surround it with quotation marks. All two word help entries require that. For draconic, the issue is a little deeper since it's matching the power name instead of the help file entry so that'll have to be looked into.

________________________________
From: byzanthia ***@***.***>
Sent: Friday, May 10, 2024 2:18:43 PM
To: torilmud/issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [torilmud/issues] help sorcerer mentions two other help pages which I can't pull up (Issue #1054)


help sorcerer

SORCERER

Sorcerers are innate spell casters who have been born with access
to arcane power. The spells at their command are channeled from
their innate affinity and do not come from a deity, or a spell book.
Sorcerers specialize in offensive magic, and their melee capabilities
are very limited. Access to metamagic and other powerful incantations
more than make up for this shortcoming.

Sorcerers may choose a subclass by using the "class" command at an
inn.

Subclasses:             Draconic, Wild Magic

Allowable races:        Human, Drow, Elf, Halfling, Gnome, Yuan-Ti,
                        Half-Orc.

Minimum stats:          STR: 50   DEX: 40   AGI:  0   CON: 50
                        POW: 0   INT: 90   WIS: 0   CHA:  0

                        For information on stats, please type:
                        "help class stats"

Sorcerer skills:         For an up-to-date listing of the available
                        invoker skills, spells, and their levels,
                        type: "help skill_sorcerer"

Equipment usage:        Sorcerers fall into the Magic-User
                        classification of item restriction.  This
                        means they have the smallest range of weapons
                        that they can wield and a very small range of
                        armor from which to choose.  They have almost
                        no restrictions on what miscellaneous magical
                        items they can use (wands, staffs, etc.)

Sorcerers can improve their skills by using the "practice" command in
their guild.


See also:  MAGIC-USER, PRACTICE, GUILD, SKILL_SORCERER, SKILLS,
           SPELLCAST, SPECIALIZE, MAGIC, SUBCLASS, DRACONIC, "WILD MAGIC"



However, when I try to find out more about draconic and wild magic, I just get two powers:

help wild magic;;help draconic


Name             : Wild Magic Storm
Type             : Enchantment
Target           : Self

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Add combo cost trigger effect for 30 seconds
Self Effect      : --> Allow a free use of Chaos Storm

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
When affected by this, the Sorcerer may cast a free Chaos Storm.

Name             : Draconic Majesty [dm]
Type             : Spell
Prepare          : At will
Target           : Self
Recharge         : 1 minute
Restrictions     : Standing, Can Speak

Effects:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Self Effect      : Add inflict spell damage trigger effect for 20 seconds
Self Effect      : --> Modify inflict spell damage by +20% for 20 seconds

Description:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
The primal power of draconic might infuses the caster upon completing this spell.
While infused with this power, the caster's innate link to sorcerous magic intensifies,
causing bonus damage to be applied to every spell cast while under the duration.



Was that intended? I was hoping to read more about the subclasses, not specific powers.

**Comment by byzanthia** [comment]
Thanks - I tried quotation marks, but that doesn't seem to help:
```

help "wild magic"
There is no help on that word.
```

**Comment by marthammor** [comment]
Hmm.. okay. Might actually be missing then! Lol. We'll get it sorted, thanks!

________________________________

**Comment by xanza-tey** [comment]
they're listed under 'help sorcerer wild magic' and 'help sorcerer draconic'
they're not extensive, but it gives the break down sub class spells by level

**Comment by marthammor** [comment]
I've got a fix in for this to correct the help file names in help sorcerer. Just needs moved in.

________________________________

**Comment by byzanthia** [comment]
Thank you!
