### ISSUE TITLE
Bug/Enhancement: Slither

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#106]
No message is provided by the mud after reclining and slithering past something.

**Comment by beshaba-toril** [comment]
I don't recall it saying anything when "scooting" past something either;
only going over someone who is reclined.

On May 20, 2017 12:28 AM, "Nyyrazzilyss" <notifications@github.com> wrote:

No message is provided by the mud after reclining and slithering past
something.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/torilmud/issues/issues/106>, or mute the thread
