### ISSUE TITLE
Generic mob races like "reptile" and "animal" - do they default to a specific sub-race (dog or snake)?

### ISSUE THREAD

**Issue by byzanthia** [torilmud/issues#1076]
https://github.com/torilmud/docs/wiki/Races mentions some races are not working right and default to others.

E.g. it says reptile defaults to snake, and animal to dog.

Is that something you could check please? I'm writing a zone with several mobs of those races and they'd look odd if they default to a specific animal rather than just "animal" or "reptile."

**Comment by marthammor** [comment]
Fairly sure they still default to those other races. I've not looked into why, but I suspect it's how the coding is read in from the area file rather than on purpose.
All code work is on hold currently until after the new class updates, and even then maybe for awhile after to allow things to settle down and get class big fixes and adjustments in.

________________________________
From: byzanthia ***@***.***>
Sent: Tuesday, July 16, 2024 1:30:14 PM
To: torilmud/issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [torilmud/issues] Generic mob races like "reptile" and "animal" - do they default to a specific sub-race (dog or snake)? (Issue #1076)


https://github.com/torilmud/docs/wiki/Races mentions some races are not working right and default to others.

E.g. it says reptile defaults to snake, and animal to dog.

Is that something you could check please? I'm writing a zone with several mobs of those races and they'd look odd if they default to a specific animal rather than just "animal" or "reptile."

**Comment by shevarash** [comment]
This is out of date, those race codes work fine now. I used them for familiars, and all looks good:

```
Description:
A sinuous black snake coils silently in the shadows, tongue flicking.

Race: Snake
```
