### ISSUE TITLE
Aggressive toggle and botting

### ISSUE THREAD

**Issue by Zipalodok** [torilmud/issues#110]
Why is there built in support to be a robot?

Aggr toggle is basically a built in robot. With a rogue it will auto backstab any aggressive mob. With casters it will engage when mobs cast offensive. With others it auto engages targets instantly.

Why is there built in support for being a robot? I'd like this feature disabled all together.

 Then for whatever reason it is auto on for any new character made. Made me auto backstab CHP guards. Which is not cool. I'm sure other such mobs have the same issue.

**Comment by Nyyrazzilyss** [comment]
Maybe remove guard from paladins while you're at it?

I can't speak for other classes, but I enable/disable this all the time on warrior. With aggressive enabled, stuff like a rogue coming in to the room doesn't always get a chance to backstab/kill someone before i've attacked it.

To say this was a problem because you backstabbed a chp guard: They're not aggressive= you wouldn't backstab them. If you had backstabbed them, that would be a problem with someone else having already attacked them unrelated to aggressive.

**Comment by shevarash** [comment]
It seems a little extreme to call this built-in support for botting, but I do agree that it shouldn't be on by default for new characters. I'll leave this open for further discussion and to turn it off by default for new characters.

**Comment by Zipalodok** [comment]
If a rogue can just toggle aggressive and follow leader. How is it not built in botting? It doesn't just engage for a rogue, it will automatically BackStab targets. Basically automates use of one of rogues main skills. Not sure if other classes use skills to auto-engage with aggressive.

**Comment by Inames** [comment]
I don't recall it ever being on by default for new characters. I've never typed the command to disable it on at least 40 of my 50 characters.

**Comment by shevarash** [comment]
I've confirmed that the aggressive toggle is set to OFF for all new characters.
