### ISSUE TITLE
Suggestion - convert phantasmal tendrils to area effect?

### ISSUE THREAD

**Issue by Hibbidy** [torilmud/issues#112]
Not sure if this is the right place to post this - 

Both 10th circle illusionist spells are single target only.  Tendrils would seem to be a great candidate for area effect - instead of one random target each wave as it is now.  

I love the class - illusionists are just behind in terms of usefulness in zones these days re: area damage (I acknowledge the other utility they bring, but they never get played).

Not saying they need to be uber, but an area option for 10th circle would be nice and tendrils seems a convenient opportunity.

**Comment by shevarash** [comment]
I think it's fair to say that Tendrils shoudl be evaluated. I'm not sure if making it area effect is the right move, but it is worth looking at.

**Comment by beshaba-toril** [comment]
I recall it being full area effect instead of single target when power tendrils was first implemented. It was disgusting how much it was doing. Every mob in room was getting debuffed.

If you could open the damage to area but keep the slow/hit/dam debuffs as random single target, it'd make the spell very beneficial and a viable contender.

**Comment by otebski** [comment]
As an illus i oppose the idea. tendrils are too great solo too, only decent damage spell in illus arsenal.
Nightmare as aoe would imo be better. It already has aoe effect.

**Comment by ghost** [comment]
They are no longer draggable, need to upgrade tendrils somehow.  With the long cast time.. lllusionists need something.

**Comment by shevarash** [comment]
This will be addressed in an upcoming Illusionist class overhaul.
