### ISSUE TITLE
spellfocus enchantment

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#121]
Spellfocus enchantment doesn't seem to do anything; or at least anything of any value.  It doesn't help with the main enchanter spells as far as we can see.  Anything able to be done?

**Comment by Nyyrazzilyss** [comment]
Among others, it does increase duration on timestop blur and globe. Stone/Scale are not effected.

0 sfenc - Timestop duration is 2:53
18 sfenc - duration is  3:16

Of course: If it was +18%, wouldn't it be 3:24?

**Comment by shevarash** [comment]
Spell focus works by increasing the specialize bonus past its natural limit. For enchanters, that will primarily effect the duration on skills like blur and globe. It also effects the modifiers on stoneskin and dragonscales, which are not reflected in powers info. The modifier on those skills determines how much damage your stoneskin or dragonscales can take before they are chipped away and destroyed. 

You should see a difference by wearing spell focus. It is entirely possible that the difference is so slight in practice that it doesn't really matter very much. 

With that knowledge, do you still think that it doesn't appear to do anything? We could look into adjusting the stone/scales algorithms to have a smoother distribution if neccessary.

**Comment by Adriorn** [comment]
It's not that it does zero, it's that it does nothing of any real value.  And like Nyy said about, stone and scale aren't affected.  Look at nyy's math above.  SF_Ench is the rarest one, and it is the most useless one right now.  SF_ele is next in line in terms of uselesness.

**Comment by Inames** [comment]
Regarding Nyy's math and what shevarash has described, you are assuming that SF modifies by a % of the current value. I'm gathering that it's modifying the bonus provided by your specialize skill by a % and not accounting for the base value? But that wouldn't explain why SF_heal works for shaman group heals since they don't get specialize healing... so there's a lot of missing info here. Suffice it to say, nobody feels like SF is worth using except for vokers and clerics, and some people like it on shamans. But as is the current values and effects do not make substituting health/ac/saves/resists for SF a worthwhile trade.

IDK if there's a hard cap on SF values, I've been told that there is, but I don't recall that ever being said by @shevarash so I'm not convinced at the moment. But if we could have higher SF valued items with a hard cap that'd be worth it, swapping out 3-4 items for 25 SF would probably be worth it under the current design. All these 1-2 SF_ items are not worth using in our high end kits.

**Comment by Adriorn** [comment]
I think SF is great for all classes except Enchanters and Elementalists.  I'm still not sure on its usefulness on Illusionists.  Druids, Liches, and Vokers get a really nice increase in damage from SF.  Clerics and Shamen get a huge increase in healing. 30%-40% on all those is a nice increase in damage and healing.  My Cleric/Shaman run around with 45% SF_Heal and it's noticed. 

Make SF_ENCH and SF_ELE have more affect on spells that matter.  Check out Illusionist, I'm still not convinced.

**Comment by ghost** [comment]
sf_ele def needs to apply toward embodies, if all it does is increase duration, rather than the bonus hp associated with it, it's kinda pointless, when the primary way of healing, for a solo elementalist, or even small group ele, is to dispel it and recast

**Comment by shevarash** [comment]
These are all fair criticisms and will be addressed with general class upgrades.
