### ISSUE TITLE
Can't memorize doppleganger still

### ISSUE THREAD

**Issue by Adriorn** [torilmud/issues#15]

**Comment by shevarash** [comment]
Are you spelling it: `doppelganger` ?

![image](https://cloud.githubusercontent.com/assets/24870638/21787000/542f2552-d68c-11e6-9a9a-dcfc1e043188.png)

**Comment by Adriorn** [comment]
I'm typing mem dop.

**Comment by shevarash** [comment]
Here's the issue:

I fixed the misspelling of the name, but the old spell has the misspelling. Therefore, the old spell that was scribed with the wrong name doesn't match the power name.

The fix for this would be to re-scribe it, but I'm just going to misspell the power name instead - that will make it work without any effort for players. We can fix the typo at a later date.
