### ISSUE TITLE
Raise dual wield cap for warriors

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#170]
Its capped by 50. 
Why? Where are the drow weapon masters dualling blades with grace? Dont tell me theyre clumsy.
We need more difference around, and that will add some.
Id say, especially with all the new ranger skills - why not to max its cap on warriors? 
They still have their advantages before the warriors if thats an issue.

**Comment by beshaba-toril** [comment]
I mostly agree with this. Although, I'm sure there's a reason for it (see
balance). It doesn't make much RP sense that warriors aren't masters of
martial combat.

Could raise dual wield and lower double attack, since they already have
riposte and make party/riposte possible on the offhand (to suffice the
other post).

I haven't tested tanking with 2 blades... But now I wanna try.

**Comment by Ruagh** [comment]
By lowering double attack, youre making warriors as-is (i.e. 1h+shield) even more meatshields. Im talking about warriors, not about the tanks. Right now, the class may be renamed, just to reflect their actual state.

Adding some more offense 1h+shield, maybe low-capped vital strike, would help too. But dual wield, and especially dual wield tanking should really be looked upon. Well, maybe also 2h, but thats another issue.

**Comment by shevarash** [comment]
We'll be addressing Warriors in the near future. I'm not sure that dual wield will be a component of their upgrades or not, but we'll keep it in mind. Thanks for the feedback.
