### ISSUE TITLE
duplicate powers in prompt

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#172]
< 787h/779H 145v/145V |kc +|bs +|bh +|bs +|bs +| P: std > 

When adding a power to the prompt, it allows adding the same power multiple times

**Comment by shevarash** [comment]
This is intended. I wanted it to be flexible, so that if you need to move a power around to a different slot you don't have to go through the pain of removing it from one slot and then adding it again. I figured it was sufficient to give the user tools to set it up how they want it.

I'm open to revisiting that if it turns out to be more hassle than it's worth though.

**Comment by Inames** [comment]
Perhaps if you add something to a slot that already exists in the prompt, it switches the two items? and if it doesn't exist in the prompt, it just replaces the item in the designated slot.

so with this prompt:

< *** |kc +|ts +|bh +|ss +|ev +| P: std >

powers prompt  twin strike 5

would simply swap twin strike from slot 2 to 5, and eviscerate from 5 to 2

< *** |kc +|ev +|bh +|ss +|ts +| P: std >

then

powers prompt armor splinter 1

would just replace kick in slot 1 as per it's current function.

< *** |ap +|ev +|bh +|ss +|ts +| P: std >

**Comment by Nyyrazzilyss** [comment]
2 years later, and it really doesn't matter. I don't use the prompt myself.
