### ISSUE TITLE
Make AUC channel player-usable for FT/LF broadcasts.

### ISSUE THREAD

**Issue by Ruagh** [torilmud/issues#176]

**Comment by Inames** [comment]
The auction channel is just a toggle to show auction announcements, there's no reason to make it a general trade chat channel. gcc is fine for that as well as all other game-related chat like we've been using it for for years. It's rare these days to see anyone using lfgc either, it all goes down on gcc, might as well make gcc the "general chat channel" for game related subjects. it'll still be used for LF/FT messages anyways because that's what people are used to and nobody enforces chat channel rules anymore. so don't try to fix what isn't broken imo.

**Comment by Ruagh** [comment]
You know, its a rule of a thumb. If things have their place, there WILL be a chance they will be lying there in order. If they dont, they probably will be scattered all around, littering. Yes, nobody forces, but this potentially will make GCC less junky, which is nice. And yes, separating GCC and OCC chitchat would be a nice practice for people, its a common courtesy, u'know.
