### ISSUE TITLE
Enhance: Add vnum to item keywords

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#182]
With the number of unique items now present in the game, what's starting to show up a lot more is the lack of unique item keywords.

I would assume however that all items do have an internal reference number used to identify them. Would it be possible to add this number to the keywords displayed when identifying, and allow for usage of this number in game with item manipulation commands? (example finditem 111111, wear 222222, get 123456 hole, get 123456 98765) etc. I can't however see anyone typing this directly, it really would be just in aliases - Primarily when doing stuff like dressing/sharing equipment between multiple characters.

Assuming item information is read from the drive only in a single location, I would guess this should be doable by changing that function to also add the unique identifier to the visible keyword list. Everything else should be transparent to it.

There would also need to be a restriction on part of this: I know there are some ingame quests that work by having items with identical keywords/names, and no obvious easy way to distinguish between them (Not that it's impossible, you can do so by taking advantage of item sorting in containers/inventory). Perhaps make sure those items are !id ?

**Comment by shevarash** [comment]
I'm not sure about this just yet. I'll file it as an enhancement for now.

**Comment by Ruagh** [comment]
Actually quests using the similar items with different vnums are just silly, and I have been addressing this issue before, but Silvanus had his own opinion.  Yes, we do need VNUM on identify.

For example - i have 2 different Yasmine diadems on storage, but they look the same. How could i separate them? Changing keywords to be unique would be nice. Say, "bloodied diadem" to one of them.

**Comment by Inames** [comment]
I'd be more happy with adding a custom keyword feature to the game where you can add your own custom keyword to an item, but that would get pretty ridiculous on pfile storage tracking that. So vnum distinction is a much simpler and less game function breaking way of doing it.

That being said I would agree that we need something to distinguish items better because when i have 9 bc daggers,  and 10 other items all with the 'ruby' keyword, my inventory doesn't allow me to sort through them very well with it's limited size. I end up pulling out a tiara, a couple earrings, trune studs, kv scepter, all sorts of random crap before i even get to my daggers...

Some people just didn't name their items intuitively and even with more intuitive item naming/keywording, there's going to be a lot of conflicts because there's only so many adjectives you can choose from...

**Comment by Nyyrazzilyss** [comment]
It was mentioned on gcc about adding . notation to keywords for item manipulation.

usage: finditem key1.key2.key3...

example: finditem bloody.diadem


That would work very well to make items 'unique', If sure there's still a number of items that won't be unique as is from doing that, but that could be easily fixed by having areas modify one of the keywords.

**Comment by Nyyrazzilyss** [comment]
With adding dot notation, this is no longer needed.
