### ISSUE TITLE
a row of iron stud eyebrow piercings

### ISSUE THREAD

**Issue by Inames** [torilmud/issues#188]
This item used to be 5ac and 8maxcon, literally only useful for trying to hit a con notch, it got downgraded to 2maxcon, and it is literally worthless. Stupidest downgrade ever, please fix.

**Comment by torilmud-silvanus** [comment]
While 2 maxcon may not be great, if you are within 2 points of a con notch, then it's still hitting a notch and giving you significant benefits in a relatively low powered slot.

Also, this quest is not particularly difficult.

That being said I am totally open to adding upgrade questing for this item, so that a player can put more work into it and expand its maxcon. Please email me at silvanus.oakfather@gmail.com if you or anyone else would be interested in writing some content for this.
