### ISSUE TITLE
Died to coldshield with Globe

### ISSUE THREAD

**Issue by Dhelindel** [torilmud/issues#229]
Died to coldshield with globe up

< 448h/600H 169v/170V P: std > say deeply defend
You are hungry.
You are thirsty.
As you invoke your deep blue silvered scale, a transluscent field
grows outward from it, completely surrounding you within its power.
The colors of the scale momentarily shift from deep blue to deep
red as the protective barrier surrounds your entire body.
You begin to shimmer.

< 448h/600H 170v/170V P: std > e
bs demon
End of a Dark Tunnel
Exits: -E -W
A torch is here fastened to the tunnel wall, flickering in the dark.
A demon resembling a giant octopus lies here making horrifying noises.

A summoned tako demon's hand starts to glow RED as blood.
A summoned tako demon makes a strange sound, as you place an enchanted khanjari dagger in his back.
BRR! As you hit a summoned tako demon, deadly cold fills your bones..
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...
The world starts spinning, and your ears are ringing!
Your globe shimmers, and fades into the air.
gsay Tatris Globe has Expired!

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

**Comment by Inames** [comment]
Most called proc items don't take effect until the next "tick" from the server. I get the same issue when I use timestop bracers and then try to cast a spell. I see your health didn't change when you moved so I assume you stacked the commands and sent them all at once. Which is why it didn't protect you. always assume you need 2-4 seconds after calling a proc for it to work. That being said, once called procs get moved over to the powers system it hopefully wont be an issue. since powers work closer to real-time. Until then, just be careful with it.
