### ISSUE TITLE
Various powers issues

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#26]
Various powers issues. Should probably sort these out into individual issues, but I didn't want to lose track of them.

```
Marlac GCC: 'fix mhp shield while you're at it'

Marlac GCC: 'alias is bad'

Marlac GCC: 'requiring target on one, and just doing 1 of the 2 if only 1 keyword is used'

Marlac GCC: '1 - divine blessing              just sayin'

Marlac GCC: 'did you fix the ac roll-over on group bark, also? talk about a major problem :P'

Marlac GCC: 'makes me feel like a dwarf when i'm tanking tia with an elf!'

Marlac GCC: 'only less as hairy'

Marlac GCC: 'and taller, and there are females of my race'

Ravad GCC: 'hrmm speaking of which.....is it powers tendril that aggros mounts?'

Marlac GCC: 'power tendril is aggroing entire room, instead of choosing a single target per wave, so, yes'

```

**Comment by Alurissi** [comment]
tendril post is above, divine blessing has been fixed, it can now be memed, as far as the power on mhp shield:

icy bash
icy shieldpunch

keyword icy fires shieldpunch, you actually need to specify icy bash, to get it to fire, alias need separated somehow, isp icy shieldpunch, ib icy bash, perhaps, also, both require a keyword target, so if you are fighting a single mob, engaged, and type icy bash, it asks for a target, however, if you just type bash, it fires at the current target.....the power needs to react similar, requiring a target when you are engaged on 22.warrior, fighting 30 warriors.....is just a major pain, because you don't always know what # you are facing
