### ISSUE TITLE
Song of Recovery

### ISSUE THREAD

**Issue by shevarash** [torilmud/issues#27]
Song of Recovery has been reported to not work. It is supposed to reduce the death fatigue timer.

**Comment by Adriorn** [comment]
Maybe make it be a better version of song of renewal instead?

**Comment by Alurissi** [comment]
i'd be inclined to agree, bard mana recovery is a major issue, and really prevents changing the way songs and mana usage during them works to make the class more action orientated, rather than just sing and afk for a couple hours, recovery song isn't really needed for res fatigue anymore, dying outside of group combat still is a pain, but if you are in a group, and get resurrected, what's the point of dropping the short fatigue in 1/2 the time? i'm all for keeping the fatigue on zone groups, makes things harder and more interesting when your elf tank is missing 3 con and 3 agi notches for 5 minutes.  Renewal song 2.0 would be my choice in updating this quested song, renewal song is about a waste at high levels, sure you regain some mana, but it's hardly usable in zone combat.  You spend 10 minutes to regain 350 mana, meanwhile your group suffers and complains the entire time about you singing the wrong song, doubling the benefit of renewal rate would satisfy the need to use this quested song for a purpose, and as mentioned, allow for the reconstruction of song system in the future.

**Comment by shevarash** [comment]
This will be addressed in an upcoming Bard class overhaul.
