### ISSUE TITLE
Archery ranger / 2h paladin

### ISSUE THREAD

**Issue by i982** [torilmud/issues#272]
i know its been brought up but i wanted to put it here because writing something down is easier than just trying to remember it.

ok so since phase 3 of paladin changes with the fix of 1hand abilities and changes to spells ive done some pretty extensive testing while i know others seem to think 2hand out performs 1hand it just doesnt. 2 hand is very weak compared to 1hand as far as damage. im not sure if its frequency of procs on avenger or the weapon itself just being weak but with 2handed using avenger even vs evil/dead targets 2hand is very very weak on damage compared to 1hand. this didnt make sense to me as 1hand is meant to be the take damage protect self mode and 2hand was more take damage inflict damage for aoe threat mode. just and idea to look into.

on to rangers

ranged, which i know has been said, is considerably weaker than dual wielding. so much so that the only time range is viable is to try to lure or when globe runs out. its just not what it should be. especially for a call called "range"r:p

**Comment by ghost** [comment]
archery rangers need 3 things really

1.  since you lose all defensive skills, parry/riposte, increase dodge, much like paladin's 2h increased parry

2. need a 3rd power that hits wraith forms, only having the 2 longest recharge work, is a major let down

3. ranger should aquire a skill, similar to paladin, when arching, paladin gets bonus to hitroll for wielding 2h, ranger should aquire a similiar feat for arching, as there are like no bows with hit/dam

as far as paladin goes,

I do agree decreasing the damage from 1h skills is a major up in the right direction, but also think the 2h skills need to have effect duration looked at, 1 round, just isn't enough, also, where's the special 2h only spells? ranger gets a couple that only work for archery, paladin seems to get none for 2h skills, i could be wrong, wasn't impressed with duration on most paladin spells, so i really haven't played with it much

**Comment by shevarash** [comment]
The Paladin issue was, I believe, due to an issue with damage calculations that has since been fixed. The Ranger archery issues have been addressed with an update today. Closing this, but please feel free to open a new issue if needed.
