### ISSUE TITLE
bleed proc mort, perm loop

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#296]
sometimes, you get stuck in a loop, from the bleed proc, where your innate healing is enough to keep you alive, but not enough to get you to the point where you can do anything, i've found several times where i'm bouncing between -3 and -9 hp, but never dying, or being able to try and bandage myself.  I'd advise either setting a solid cap, at 0 hp for bleeding, it won't take you below 0.  or, you could give us a command to just die, if we're setting morted in this loop for a period of time.  mostly, this happens to lower level chars, or younger age chars

**Comment by otebski** [comment]
I believe quit can be used to die when morted, at least should. But it has this warning message about dropping equipment and i never had guts to try it out.

**Comment by shevarash** [comment]
This has been adjusted so that you won't lose any hit points if you are below -5. This should mean that if you recover from being incapacitated you have a brief window to bandage yourself and get rid of the bloodloss. Before, it only stopped hurting you from -9 to -5, which is what allowed players to get stuck in the endless loop.
