### ISSUE TITLE
item type: treasure auction

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#298]
need to open up auction for items flaged with type Treasure, if it has value and stats, it should be auctionable!

**Comment by ghost** [comment]
also, there's other items that should be auctionable, but are not, check out goggles of the deep, from embay, nothing in id shows why it is unauctionable

**Comment by OghmaToril** [comment]
I have a theory that goggles of the deep aren't auctionable because of the value assigned to them, but I'm not sure on that.

**Comment by torkur** [comment]
I reported this too a few months ago.  Silvanus I think was looking into it and had a theory.  My report was with Trollbark items like the Azurite ring and Mystical Crystal Skull not being auctionable, but the serpent armor is.

**Comment by OghmaToril** [comment]
The reason Azurite Ring and Mystical Crystal Skull are not auctionable is because they are type Treasure.  That was specifically coded in that way as many quest items are type Treasure.

The better question to ask is whether the ring and skull should be changed to worn/armor and pspcrystal respectively.
