### ISSUE TITLE
New powers info list

### ISSUE THREAD

**Issue by odinson1975** [torilmud/issues#346]
For rangers powers list i noticed some are miscategorized

Arctic Barrage                      [ab    ]   At will         5th circle
should be bow not at will

Hail of Thorns                      [hot   ]   At will         4th circle
should be bow not at will

Lightning Arrow                     [lita  ]   At will         3rd circle
should be bow not at will

**Comment by Inames** [comment]
They are classified as At will, rather than Study like most caster spells, because you don't have to memorize/pray for them to cast them. That being said it is clunky and misleading listing them as at-will, I also agree that listing them by weapon type would be a better option, the same should apply to pal/blk spell list.

Since all ranger/paladin/blackguard powers recharge/operate in the same manner, it should be a given that they are at-will(with a recharge) once you are familiar with their operation. I also think there could be another term to use for spells cast from a pool of slots besides "at will."

**Comment by OghmaToril** [comment]
These are properly categorized.  At-Will is an indication that the spells are spontaneous casting.
