### ISSUE TITLE
Renting In Ashstone

### ISSUE THREAD

**Issue by zenevan** [torilmud/issues#357]
renting in ashstone results in being sent to vt.

**Comment by Inames** [comment]
There's a lot of missing context from this I feel, do you mean to say you rented in Ashstone, then logged in in VT? Did you go to VT after a crash when the last time you rented was in Ashstone? What is the class/race/hometown of the character in question?

**Comment by marthammor** [comment]
I know what caused this and its fixed and awaiting testing before it gets moved in. I added the ability to flag rooms as !camp instead of an entire zone. Along with that change, I fixed a possible loophole that would allow a player to stay in a !camp room/zone while the mud was rebooted. The game 'rents' you on a reboot and places you back in the same location when the game comes back up.
Anyway, the entire Ashstone zone is/was flagged as !camp, so even though you rent out proper, the game now thinks you're coming back from a reboot and sticks you in the cushy room that exits to VT.
Probably a lot more information than you wanted, but there ya go!
