### ISSUE TITLE
consent for drag and res

### ISSUE THREAD

**Issue by ebouchard88** [torilmud/issues#376]
With the current death system in place, I don't think the consent for drag and ress is still a valid restriction. It would make it easier if it was removed.

**Comment by shevarash** [comment]
Thanks. This topic is worth investigating.

**Comment by Zipalodok** [comment]
Rather see a "You can't res this Target, lacking consent" message instead of it casting. I'd personally like to retain my ability of giving consent for things. One could drag a AFK dead SM player, then res them in pits and such, etc.
 With command "consent" its relatively easy to confirm consent for drag, having no consent for drag could cause non-draggers to drag while someone else is attempting drag. Adding a echo to player you're attempting to drag, would be nice though.
