### ISSUE TITLE
Comeback strike suggestion

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#379]
Comeback strike is currently healing for 50 hitpoints with a 12 second recovery on my ogre.  I'd suggest that comeback strike should use strength to modify the hitpoints it returns, subject to balancing of course.  Since sword and board seems to be the main tanking setup that would increase the tanking ability of the lower agility strong races (ogre, troll, duergar, dwarf).  It would also make it less useful for the high agility weaker races (elf, drow) and could lead for some variations in strategy for how you tank for the race types.

My "perfect world" Example: Ogre receives 100 hp per comeback strike so they spam it whenever it is up and make for good "boss" type tanks. Elf only receives 15 hp per comeback strike which is helpful, but not nearly as useful as other skills for situations.  Given their higher agility, though, they're still the main "mob group" tanks.

**Comment by shevarash** [comment]
Interesting idea, though I'm not sure just yet if we want to implement this big of a difference between races. I'll keep this open and keep an eye on it. Thanks!

**Comment by Zipalodok** [comment]
I like this. Especially since removing crit from str and putting it on weapons, basically nerfed ogres in the process. This would open that back up, while adding some strong depth to stats. Which seems to lack in most areas currently to me. I'd love to see more features used like torkur stated. That have more backbone to your skill level and attributes.

**Comment by shevarash** [comment]
Races are due for some balancing, but this isn't quite the approach we're going to take. Thank you for the feedback!
