### ISSUE TITLE
Psionicist Powers List? Please?

### ISSUE THREAD

**Issue by i982** [torilmud/issues#396]
im just assuming this class due to the fact no one plays it has to be close to getting its day in the ressurection chamber... however... if it isnt can we please get a powers list for them like all the other classes? even illithid innates dont have a powers timer like half orcs and such. ive noticed playing it more in areas that require certain skills (rainbow curtain) leaves you commiting suicide just to see if your innate is ready... can we please get a powers list so we know what the powers do based on skill levels or whatever the case may be?

**Comment by Nyyrazzilyss** [comment]
Illithid doesn't have a powers list because they don't have any 'powers'. Everything on illithid is old code. Being present in a powers list is because the old code has been re-written to the powers structure.

At such time as the class skills are rewritten by nature it would show up in a powers list.

**Comment by i982** [comment]
please just stop responding to my posts.

**Comment by OghmaToril** [comment]
This will be resolved once the Psionicist class is updated and all abilities are converted to powers.
