### ISSUE TITLE
Most bard songs don't actually do anything

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#452]
Song of Sorcery today reported no noticeable benefit
Song of Elements maybe works on one person a round
Song of Recovery doesn't do anything
Song of Protection doesn't do anything

**Comment by shevarash** [comment]
Bards are a problematic class. Rather than try to fix individual songs we're going to overhaul the whole thing. I don't mind fixing _bugs_ in the mean time though. Do you think these are bugged or just not helpful?

**Comment by Dartan82** [comment]
Sorcery back when it was reduced quick chant was decent.  If it made people mem faster it would be nice too.  If I could target one caster to mem faster really fast that would be even better.  

Protection just doesn't do anything period according to an attribute compare before and after the song.    If this gave all saves or agi bonus or protection from fire/coldshield it would be awesome.

Recovery just doesn't do anything anymore from what I hear.  Even now with the way res effects work it would need to do something like negate res effects and heal less than song of healing to be effective.

Song of Elements needs to be compareable to offensive harmony.  

While we are on the topic...

Not sure if defensive harmony is actually that great.  Back in early 2000's we noticed it increased skills but didn't do much.

I hear miscast magic doesn't do anything.  If it does then making it more obvious like the mob miscasting due to the song would be good.

Revelations is useless because of spells and gear

Travel is useless now because of fly items/spells/procs/aura of griffon.  Might as well have song of healing or recovery give mv as well.  Also put the memorial portion somewhere else :/

Song of harming not good because the damage vs. the boost from offensive harmony isn't worth it.

Song of regen worthless because you get song of healing at lvl 31

**Comment by ghost** [comment]
protection does do something, at full strength, its -5 to all saves

elements adds elemental strike damage to attacks, it's not permanent, nor is it everyone at once, but it does work

travel has many uses, group fly for quick traveling, and consistant move regain on a bard running the globe (omg people walk?)

song of harming is epic, as it instantly engages you into combat, as well as dishes out aoe damage

regeneration is a good song, but i'd like to see mvs added to it, understand it's only for those below healing level to do some healing

miscast magic is a pain, because you have to give it a target, but it does make mobs abort casting, just like chessboard whip, it's not 100% no casting from you!

restoration, needs to be an upgraded song of renewal, it's a quest song, and should update the strength of renewal like healing does with regeneration

sorcery i don't really think does anything in today's world

revelations should be upgraded, this would be perfect for unhiding, and searching via bard song!

defensive harmony doesn't really give a noticable effect, though i think it should be a group stoneskin spell! very low level, maybe 1 hit poof, at begining, and topping out at 3 hits of stoneskin when song is full strength, given each tick of the song

so yeah, i can't believe you didn't notice any stat chance on protection, for reals :P there is a good time to use that song, and when i show people, they always use it afterwards :P

**Comment by Dartan82** [comment]
I was probably wearing gear and at first tick song of protection is only -3 saves so it's not very noticeable.  even -5 saves on endgear isn't really that great.  will try it on the other stuff you mentioned.  

I kind of wonder if sorcery did work with cast and not with powers since it's two different systems.  I do remember it saving a *.

Miscast I thought did interrupt but heard it's broken again

**Comment by Inames** [comment]
Miscast interrupts the old spellcasting system spells, pretty reliably at max skill with a decent mandolin. But except in very few small-group situations it's almost entirely not worth using as a single-target song. Consider making it a room-wide effect.

Elements already has a significantly higher damage output than Offensive Harmony, provided the melee group members already have another source of haste. And in most cases even without haste, but it's a mana hog and not feasible to run often, or against mobs with MR.

Sorcery used to improve on spellcasting skills making it harder to abort highest circle spells, that's not a thing anymore. It doesn't directly affect skills so any improvements that may have been there for specialize skills don't affect damage modifiers on powers. I can't confirm the cast time reduction, I don't remember ever considering that or noticing it.

Travel is fine as it is, the fly bonus and super mv recovery is sufficient.

I think a good update for Recovery would be to bring it to a 1/2 healing rate heal, like it was before, give it like 1/2 the regen rate of renewal, and 1/2 the regen rate of travel, as well as updating it to tick off ress fatigue from the new timer. This way it's not the most effective at any of the specialized song tasks, but you aren't made completely useless while you renew, and it will serve the same old function of aiding ress recovery.

Song of Protection is great for a group of newbs without gear, it gives pretty good AC and some saves, I'd like to see it grant resistances, or take a leaf out of the Duris book and make it grant stoneskin and major globe, that would bring it to end-game zoning usefulness and force a significant choice between healing and buffing.

Harming, Revelations, Defensive Harmony/Disription, and to some extent Offensive Disruption are all fairly useless these days.

**Comment by shevarash** [comment]
This is all great information and I appreciate the feedback. I'm closing the ticket, but this will be reviewed again as I work on Bard overhauls. Thanks all!
