### ISSUE TITLE
Removing item by slot

### ISSUE THREAD

**Issue by Dartan82** [torilmud/issues#480]
For example, you can type remove primaryweapon to remove primary weapon.  Can we also get alias by slot like wornhead or slothead to remove what is being worn there please?  Thanks!

**Comment by i982** [comment]
i support this message!!!!!!!!!!!!

**Comment by marthammor** [comment]
Because this was easy, I picked on this.
So far I have for keywords:
all, badge, head, eyes, lear (left ear), rear (right ear), face, neck1, neck2, about, quiver, body, arms, lwrist (left wrist), rwrist (right wrist), hands, lfinger (left finger), rfinger (right finger), shield, held (only works on one held item if holding more than one, currently), primaryweapon, secondaryweapon, compbag, waist, tail, legs, feet.
Am I missing anything, or are there any keywords you'd like changed to something else?

**Comment by Dartan82** [comment]
Looks solid.

**Comment by CountVooku** [comment]
Awesome!

**Comment by ghost** [comment]
something, and the only real thing i can think of, which you should check into before rolling this out, is hulburg slime whip, it is susposed to eat you when you remove it, check to make sure removing by slot still has this effect!

**Comment by ghost** [comment]
oh, and valhalla stuff, blur/deathpact/haste, um...yeah

**Comment by marthammor** [comment]
Okay, so I was requested to clean up the code a bit on this (it needed it) so the keywords have changed. Here is the list of keywords direct from the code:
  "Finger",
  "Finger2",
  "Neck",
  "Neck2",
  "Body",
  "Head",
  "Legs",
  "Feet",
  "Hands",
  "Arms",
  "Shield",
  "About",
  "Waist",
  "Wrist",
  "Wrist2",
  "Weapon",
  "Offhand",
  "Held",
  "Eyes",
  "Face",
  "Earring",
  "Earring2",
  "Quiver",
  "Badge",
  "Tail",
  "Component"
As a side effect of this, the old keywords 'primaryweapon' and 'secondaryweapon' will no longer work and you'll instead use 'weapon' and 'offhand'.
Removing an item by slot name shouldn't effect any procs that happen when you remove an item as the same functions are still called to actually do the item removal (I tested valhalla and it works fine).
Note: The names do not have to be capitalized. Code will check both capitalized and non-capitalized keywords.
