### ISSUE TITLE
align quests

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#486]
can we get objects for these quests, which are obviously used in more than just align work, made to repop?

**Comment by shevarash** [comment]
Which exact items are you referring to?

**Comment by Inames** [comment]
Just look at all the objects in the qst files for them, for example, the quest to step toward evil requires the mushroom paste quest from longhollow, which can only be done once per boot because the mushroom itself only spawns once per boot. for the same quest I think the daughter's head only spawns once per boot. I've never done any of the other 3 so I can't speak to those.
