### ISSUE TITLE
ancestral shield

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#49]
cast version, stays for duration of spell, no matter how many spells are fired at it in the time frame

powers version, only lasts until it runs out of time, or is hit, by a single spell

would like to see the spell stay for duration of the spell, so as, not to have to recast it every other round, shamans don't do much, but there are other things we could cast too!

**Comment by shevarash** [comment]
It doesn't look like the powers version always dissipates when hit by a single spell. I can recreate the following effect pretty easily:

> Your ancestral shield absorbs some of the spell! 

It turns out that there is a simple chance to destroy the shield each time, from the spell or the power. However, I did find a separate issue with the spell that could account for some of the strange behavior you're seeing and I fixed that. I think this should work as expected now.
