### ISSUE TITLE
Rules: Don't attack shopkeepers

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#552]
help rules

7. Do NOT kill OR EVEN ATTACK shopkeepers, stable masters, guildmasters,
   ferry captains, guildguards, innkeepers, or bankers FOR ANY REASON
   even outside of hometowns.  These mobs are made for explicit reasons
   that relate to the play of the mud.

Rikna 'I'm looking through the rules and some things seem oddly 
specific, like with the NPCs, for example, why allow them to be 
attacked at all if you don't want them to be attacked?'
You 'I'll github that. I'm guessing you're looking at a rule 
that dated back to Sojourn (the 1990s) about shop keepers'
You 'If you can attack it, you can kill it (maybe!)'
Rikna 'Oh sorry! I thought that was recent haha. I just dont 
want to end up attacking something that isn't supposed to be 
attacked.'
You 'Almost 30 years ago now on the mud there was an issue with 
people killing shopkeepers. That's where that rule had come 
from'
You 'The code was changed years ago though to make some rooms 
!combat so you couldn't attack them. The rule though was never 
updated'

**Comment by shevarash** [comment]
We have an internal project to update the rules. I'll keep this here as a reminder.

**Comment by beshaba-toril** [comment]
Still had an issue with this lately. I think the rule needs to remain in place until bugs are worked out.

Have this as a part of the Rules update project. Closing ticket.

**Comment by ghost** [comment]
i'd say fix the code already, adding 1 word into the code takes what? 30 seconds?  no, lets roll out more untested and incomplete powers..........but yeah, while you're at it, put beshaba out to pasture where he belongs.  forcing renames seems to be his only job, and he's failed at that to the point we get stupid fucking names like adriorc, and badase as acceptable, but only because of who the char is linked to irl.

**Comment by ghost** [comment]
and as he seems to wanna take a jab at me, i would like to point out, just because you put a nokill mob in a non SAFE room, does not mean that killing mobs in that room, is wrong.  People do it every day.  The day you do it with an aoe, that angers the nokill mob, you're flag'd as rule breaking, called spamer, and baned............nope, sorry, your shit, not mine, if you are gonna pick and choose what can and can't be used in each room, then make a damn list and post it, assholes.

**Comment by ghost** [comment]
the room 1d of sm inn is NOT A SAFE ROOM, get this thru your head folks, just because you choose to idle there, or use a robot psi whos' standing there, doesn't make it offlimits to others playing the game, and if a MOB is spamming, don't blame a player for spaming, this is stupid, and i still say it's another attempt in a many years long mission, by beshaba, to run me off for good, which he has, good job, i can see why shevarash granted you god status.  You are so honest and trust worthy and fair to all!
