### ISSUE TITLE
Haste improvements

### ISSUE THREAD

**Issue by Alurissi** [torilmud/issues#57]
i'm sure i'm not the only one noticing that haste really isn't all it's cracked up to be.  when you can max out dual wield, weapon skill, and double attack on a rogue, and because you aren't khanjari human or a halfling, and sometimes a gnome, you are consistantly held back in hits, i'm finding that dwarf/half-orc/duergar all are facing the same thing, averaging 3 hits per round.  double attack and dual wield should be 4 hits, haste should add atleast 1 hit to that, but for the most part, it just isn't happening.  I'm wondering if perhaps there's an issue with haste and races.  on warriors of various types, seeing 3 hits is common, so the haste and double attack is fine, but when a rogue or dire/ranger can max out dual wield much higher than warrior's 50, why isn't haste hitting offhand weapon?  why does it seem that 6 hits on a halfling, and 4 hits on a dwarf, with max stats, and same eq, is right?  even non khanjari humans are getting more than dwarfs and half orcs! what gives?

**Comment by Inames** [comment]
I always used to think it was:
Standard Attack = 1 hit from Main Hand
Dual Wield = 1 hit from Off Hand
Haste = 1 hit from Main Hand
Double Attack = 1 hit from Main Hand
Racial Bonus = Occasional 1 hit from Main Hand

What it actually seems to be:
Standard Attack = 1 hit from Main Hand
Dual Wield = 1 hit from Off Hand
Haste = Chance of 1 hit from Main Hand, Chance of 1 hit from Off Hand
Double Attack = 1 hit from Main Hand
Racial Bonus = Occasional 1 hit from Main Hand

TL:DR Haste Absolutely makes you hit more with BOTH your primary and secondary weapons. And any other difference in attacks per round is due to skill level in double attack/dual wield, potentially class, and of course racial dex modifiers. You simply cannot get more than 1 off-hand attack without haste, and double attack is simply an extra attack from your main hand, and dual wield doesn't have a chance to proc double attack on your offhand, or visa-versa. All rogues seem to be getting a consistent 4 attacks (2 per weapon) each round with max dual wield and slightly lower than or maxed double attack, and racial dex modifiers give them potentially 5, but never 6(maybe on a halfling, definitely not an elf, but my halfling rogue's double attack isn't maxed yet so I can't test to be sure). But it seems to be specifically an issue with rogues and is likely due to the low skill cap of double attack, because ranger/dire who cap double attack slightly higher do not have this issue at all. Warriors/Classes who cap double attack higher typically get as many as, if not more attacks than rogues on a consistent basis depending on whether they dual wield or not.

Here's what I found from testing with my Half-Orc Dire
Wielding a Bludgeoning weapon in my Primary Hand, and a Piercing weapon in my Secondary Hand

```
Standard Combat Round without Haste
Bludgeon (Standard Attack)
Pierce (Dual Wield)
Bludgeon (Double Attack)
- This was the most common combat round that happened almost every time. Occasionally a Pierce or
second Bludgeon wouldn't happen.

Standard Combat Round with Haste
Bludgeon (Standard Attack)
Pierce (Dual Wield)
Bludgeon (Haste Attack)
Pierce (Haste Attack)
Bludgeon (Double Attack)
- This was the most attacks that ever happened while hasted. Very often the case was that the second
Pierce attack never occurred. Leaving the combat round at 3 Bludgeons and 1 Pierce. Occasionally it
simply occurred like a non-hasted combat round with 2 Bludgeons and 1 Pierce.

I never saw an occurrence where there wasn't at least 2 Bludgeons while Hasted.

I suspect that haste simply affords an extra opportunity to hit. and it is not a guarantee to hit.
Furthermore I never saw an instance where there was not at least 1 Pierce, unlike in the non-hasted
standard combat round.
```

Here's what I found from testing with my Moon Elf Ranger
Wielding a Bludgeoning weapon in my Primary Hand, and a Piercing weapon in my Secondary Hand
```

Standard Combat Round without Haste
Bludgeon (Standard Attack)
Pierce (Dual Wield)
Bludgeon (Double Attack)
- This was the most common combat round that happened almost every time. Occasionally either a
Bludgeon would not occur, or an extra Bludgeon(Racial Bonus) would occur. I never saw an occasion
where a Pierce did not occur. Conversely I also never saw an occasion where a second pierce Occurred.

Standard Combat Round with Haste
Bludgeon (Standard Attack)
Pierce (Dual Wield)
Bludgeon (Haste Attack)
Pierce (Haste Attack)
Bludgeon (Double Attack)
- This was the most attacks that ever happened while hasted.

I never saw an occasion where there wasn't at least 2 Bludgeons. Occasionally either a Bludgeon
would not occur, or an extra Bludgeon(Racial Bonus) would occur.

I never saw an occasion where a second Pierce did not occur. Conversely I also never saw an occasion
where a third pierce Occurred.
```

**EVERYTHING BELOW HERE IS SPECULATION, THEORY, AND CONJECTURE AND MUCH MORE TESTING WOULD NEED TO ENSUE TO PROVE OR DISPROVE IT WITHOUT SEEING THE SOURCE CODE OR HAVING IT AFFIRMED/DENIED BY ONE OF THE GAME'S CODERS**

I hypothesize that the combat engine uses some sort of "attack speed" mechanic, where for example, an attack speed of 1 on your main hand, suggests that you will always get 1 attack from your main hand. and an attack speed of 1.5 on your main hand, suggests that you will always get 1 attack from your main hand, and a 50% chance of a second attack on your main hand. The function of double attack and haste could simply increase this "attack speed" stat and giving it numbers higher than 2 guarantees 2 hits per round with a chance of a third. The Racial Dexterity Modifier would further increase this but I believe this is a random modifier based on the Dexterity Stat of the character, whereas Haste/Double Attack/Dual Wield are static modifiers, or at least have a much smaller range of fluctuation. Lastly I believe that this mechanic applies separately to each "hand" in the calculations.

I suspect that the Base Attack accounts for a value of 1 on the Main Hand.
I suspect that the Haste modifier accounts for a value of 1 on the Main Hand AND the Off Hand.
I suspect that Double Attack offers a static value or only slightly variant value applied to the Main Hand.
I suspect that Dual Wield offers a static value or only slightly variant value applied to the Off Hand.
I suspect that the Dual Wield value sets the Base Attack Speed for the Off Hand
I suspect that Dexterity offers a random value applied to the Main Hand AND the Off Hand.
I suspect that Dexterity only affects these numbers by a value beyond the standard 100, which is why you don't typically see extra attacks on Races with a negative or ZERO racial modifier.
I suspect that Dexterity applies a lesser amount of attack speed on the Off Hand.

I will offer some example numbers to illustrate the idea in a manner that would suggest it fits the pattern of the above combat round standards. These numbers are simply speculation and I'm not claiming any real knowledge of the numbers behind the code.

**For Example:**
```
Main Hand: Base Attack + Double Attack + Haste + Dex Mod = Attack Speed/Attacks Per Round
Off Hand: Dual Wield + Haste + Dex Mod = Attack Speed/Attacks Per Round


Half-Orc: Base Dex 100 (0 Modifier)
Main Hand: 1 + .6 + 1 + 0 = 2.6/2-3 Attacks Per Round
Off Hand: .85 + 1 + 0 = 1.85/1-2 Attacks Per Round
Total: 3-5 Attacks Per Round
This suggests 2 Attacks Minimum with an occasional 3rd from the main hand, and 1 Attack Minimum,
with a more frequent 2nd attack from the off hand.


Moon Elf: Base Dex 115 (0 to .5 Modifier)
Main Hand: 1 + .6 + 1 + 0 to .5 = 2.6-3.1/2-4 Attacks Per Round
Off Hand: .85 + 1 + 0 to .5 = 1.85-2.35/1-3 Attacks Per Round
Total: 3-7 Attacks Per Round
This suggests 2 Attacks Minimum with a frequent 3rd and occasional 4th from the main hand, and 1
Attack Minimum with a much more frequent 2nd attack from the off hand. A 3rd attack never occurred
from the off hand, suggesting that there may be a hard cap on the number of attacks.
```

**Some other notes...**

I watched some attacks on my Rogues as Human, Halfling and Moon Elf, and I noticed that they more rarely acquired the 3rd attack from the main hand, suggesting that Double Attack may play a much stronger role in the number of attacks by the main hand but also that the Human never saw this 3rd attack at all thus the Dex Modifier also plays a huge role in the 3rd and sometimes 4th attacks from the main hand. But I never saw less than 2 attacks from the off hand while hasted on any race.

In light of the fact that the human rogue never saw a 3rd attack from the main hand, I suspect that haste may in fact play the role of a multiplier rather than a static value in the equation.

The number of attacks from the serpent circlet seem to double while hasted versus not being hasted. which further suggests that haste plays the role of a multiplier rather than a static number.

Another strange occurrence during my testing was that there were occasions where the training dummy I was testing on made absolutely no attack against me (no miss/dodge message at all). So there may even be a fluctuation on the base attack speed making it less than 1.

I further my argument for this "attack speed" mechanic by referencing the fact that my dire would always get at least 1 attack from the off hand, but not always 2, this is probably due to the fact that my dire's dual wield skill is not quite maxed... But consider this... if there's a chance to not get an attack due to lower skill, surely there would be a chance to not get either attack from the off hand in a single round. But alas, it NEVER happened. However, on a lower level ranger with significantly lower dual wield, there were several rounds where I didn't get either off-hand attack. so it should be possible with less than adequate skill to not get either off hand attack. But the dire ALWAYS got at least 1 off hand attack suggesting that some mechanic guaranteed that hit to occur. Also, despite being hasted on the lower level ranger, I NEVER got a second attack with the off hand weapon, surely it must work in the other direction as well that it must be possible if the attack is based on skill that it may be possible for two off-hand attacks to occur from a low skill, hasted ranger.

Unfortunately there is always the possibility that these extra attacks from haste are simply based on a threshold factor of the skill pertaining to that hand and the special extra 3rd/4th main hand attacks from racial dex mods are determined after the fact. And the human and non Elf/Halfling races not getting 3rd main hand attacks could be due to racist/classist code limitations... But that would be boring... and wouldn't explain why humans NEVER get a 3rd main hand attack despite haste/double attack stacking on top of the base attack and elves getting that 3rd attack and even rarely a 4th attack.

I'm also pretty sure it's not a race restriction because I get 3 attacks standard on all warriors with haste and even my human anti/paladin but also get the extra 4th attack from my elf/halfling warrior. So I suspect the lack of attacks on human/dwarf rogue must be due to both the low double attack cap, and the fact that they aren't benefiting from a dex modifier which probably makes all the difference assuming that haste is a multiplying factor of "Attack Speed."
