### ISSUE TITLE
Keprum quest: Sathawhatever requires badge turnin to upgrade but will not respond if you have no badge.

### ISSUE THREAD

**Issue by gruumsh** [torilmud/issues#592]
reported: Sathagainwhatever asks for the badge at the end of the quest, and will not respond to someone without one. 
Players tend to give them their one badge to upgrade, so its unreasonable to expect them to keep spares? 

Need more info.

**Comment by Tiamafas** [comment]
This is the step when you turn in your corporal badge and are supposed to receive your lieutenant badge.

The bug works like this:
You have to have 2 corporal badges in order to receieve your lieutenant badge. You have to wear one of them while you hand in the other. 

If you DON'T wear a corporal badge and turn in 1 corporal badge nothing happens.

Ticket #568 is about this same bug.

**Comment by gruumsh** [comment]
Thanks, that helped track it down.

**Comment by gruumsh** [comment]
Fixed & merged, see patch notes: http://www.torilmud.com/news/patch-notes-9-27-2019/
