### ISSUE TITLE
Top 5 Area Fixes - 12/2019

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#636]
so many broken area things, 0 fixes in 2 years

**Comment by shevarash** [comment]
Hi,

I know it's frustrating when things don't get fixed. We do have active staff members who work on areas issues, but we're a small volunteer team and it's pretty hard to get everything done that we'd like. It can also be really hard to sort out the most important things to fix, so maybe everyone can help us with that by participating in a little experiment.

Let's use this issue to assemble a top 5 of the most important area fixes, and I'll do my best to get them knocked out in a timely fashion. Here are the ground rules:

* Anyone can nominate up to 5 issues. 
* To nominate an issue, post a reply to this thread and list the title and GitHub issue numbers that you'd like to nominate. (GitHub tip: you can type `#` to bring up a searchable drop-down menu of issues within an issue body.)
* If your issue isn't in GitHub yet, make a new one and then post its number.
* Limit your submissions to fixes, rather than big overhauls of zones or mass equipment rebalancing.
* 5 days from now, I'll take whatever has been nominated and compile the top 5 based on the number of nominations, severity, and practicality of fixing. I'll post that list here and then get to work.

**Comment by Dartan82** [comment]
1. https://github.com/torilmud/issues/issues/590 (Bahamut)
2. https://github.com/torilmud/issues/issues/596 (Friar 11 Ashstone)
3. https://github.com/torilmud/issues/issues/605 (Trune epic)
4. Balance Oriental monk rewards or give upgrade quests
5. Fix jot so people can't just run in and snipe rares when you have a group/person combing the grid.

**Comment by Toraza** [comment]
1. Agree with #590 - Bahamut eq load crashes the game
2. #528 - Faang invasion sometimes doesn't load when quested
3. #547 - Whark hard enough as it is with all the !rent items.  Make it so he doesn't die in BG. So ppl can actually do the quests.
4. Garagos quest - make the incense rentable
5. Dealer's choice!!!

**Comment by TheHerb007** [comment]
#590 (Bahamut)
#605 (Trune epic)
Balance Oriental monk rewards or give upgrade quests (doing it right now even though it's completely not worth it)
#596 (Friar 11 Ashstone)

**Comment by Alurissi** [comment]
seeing people post about stuff they wante eq adjusted, i'll post about zone issues...

faang invasion has many issues, loading, and ogres not being flag'd sentinel for walking them to faang

baphomet 4th floor doesn't always open

several whark quests are missing consent triggers, angel of brownie for instance

hulburg is missing several door names, such as 1w of hive mother, if it's closed from west side, inside has no keyword so you can never open it

chp has a blockable entrance in sewers so you can stop mobs from tracking to king, 1 way needs removed

**Comment by saerian** [comment]
https://github.com/torilmud/issues/issues/642 - Would love to see something done to make SPOB doable again. Should be fixed with to accommodate updated powers. Really unique zone that has sat untouched for too long.

https://github.com/torilmud/issues/issues/590 - Agree with Brian on Bahamut

https://github.com/torilmud/issues/issues/528 - Faang Invasion

https://github.com/torilmud/issues/issues/640 - Baphomet 4th Level

https://github.com/torilmud/issues/issues/641 - Magma Rewards - Last time I went was as described and was pretty disappointing.

**Comment by marthammor** [comment]
> Fix jot so people can't just run in and snipe rares when you have a group/person combing the grid.
- I think this is more a rules issue and there are some discussions about updating the rules for today's game. No ETA on progress on this.

> Bahamut eq load crashes the game
- This was fixed after it was discovered.

> several whark quests are missing consent triggers, angel of brownie for instance
- Angel has a consent trigger that was added awhile back. It uses 'bow' as the action to work. If you add the other mobs that you know of that need triggers, either consent or drop (drop not always possible due to things mobs may be carrying sometimes) we can get those added.

> faang invasion issues
- I'm going to assume that these issues are with the current version of the invasion after Annam fixed some stuff awhile back?

> hulburg is missing several door names, such as 1w of hive mother, if it's closed from west side, inside has no keyword so you can never open it
- I've fixed this door so its able to be opened/closed from both sides. Any other doors like this, please list the room name or mob names that are around them and we can look them up and fix if it wasn't done for a specific reason.

> chp has a blockable entrance in sewers so you can stop mobs from tracking to king, 1 way needs removed
- Removed single file rooms from sewer.

> Baphomet 4th Level
- I _think_ this is just a timing issue where you guys are missing it by a hair, but its really hard to test solo. Not going to rule out an issue though as the mechanics are fairly unique.

> Bahamut eq, Ashstone quest rewards, Trune rewards
-Not off the table, just out of the scope of this experiment/ticket I think.

Any other issues I haven't mentioned aren't off the table for being fixed, was just commenting on the ones I've looked into/fixed already. Please keep posting your fix suggestions per the instructions above or nominating ones already listed.

To note, other issues that are awaiting move to mainmud are:
- Camping is no longer allowed in Ice Crag. The Icess is tired of visitors setting up camp wherever they want.
- Bronze scepter now repops.
- !camp added to rooms leading up to a challenge area in UM2.
- Pressure plates and portcullis' in CPV have had some maintenance done on them.
- Dragoncult robes proc wording as been updated.
- A missing message in the rot spell was updated.

**Comment by shevarash** [comment]
This experiment didn't quite work out. I appreciate all of the ideas and we've fixed a lot of it. The rest are recorded as issues that will be addressed.
