### ISSUE TITLE
Special Auction Hall

### ISSUE THREAD

**Issue by ghost** [torilmud/issues#650]
So as I've been working around testmud looking up vnums for rooms objects and mobs to use in various ways and quests, It occurs to me, that there are still a lot of the old old artifacts still in existence.  We've seen some of these come out during special occasions, but for the most part, they remain shrouded from view.

Wondering how hard it would be, to have a SPECIAL auction hall, which is no way shape or form linked to any other auction, where in there are HIGH priced norent uniques that can be purchased in a buy-it-now forum, and it changes every so often, or per boot, what is actually there and can be cash dumped on, for a boot's worth of special fun.

Also, since most of the old uniques were custom made, requiring rp stories....perhaps that could be included somehow, for nostalgia purposes.

In sticking with the other suggestions i've seen, about honoring fallen players, this special auction could also include a statue garden, with some of our lost comrades, and perhaps a story board/plaque for those wishing to share fond memories.

just a thought

**Comment by Tiamafas** [comment]
I have thought about the posibilites in re-introducing artifacts back into the game that won't affect the overall game balance. 
One possible solution would be for area makers to use them in SPOB type zones where you have to use them inside the zone in order to be able to complete it. Then you would have to hand them in in order to leave the zone or receive the zone loot. They would have to be !rent or people would just idle with them until the game crashes.
