### ISSUE TITLE
Finditem lag

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#653]
Is this because it is checking so much information, bags, storage? Or whats is the deal w it?

**Comment by Inames** [comment]
It's because "checking through all of your equipment/bags/etc takes a few minutes to be thorough" which translates to a bit of time. It also stops people from spamming the command to crash/overload the server with search inquiries that return 1000's of items because we all have portable holes and layers of bags with hoarded equipment and quest items.

**Comment by shevarash** [comment]
That's correct, the lag is to prevent spamming it.
