### ISSUE TITLE
More equipment restrictions - Less mudflation

### ISSUE THREAD

**Issue by jokkmeister** [torilmud/issues#785]
I wish to see more restrictions on equipment. As it is now you have to make better and better equipment in every new zone. But if equipment had severe restrictions you could make essentially the same level of equipment in new zones but with different flags instead. That way we slow mudflation down to a crawl instead of the dash it is now. New zones are always followed by demands for better stats on the equipment and whining about how it's not better than the gear already in play.

Make use of the racial restrictions, class restrictions and alignment restrictions. It should be mandatory for an item to have at least one of them, preferrably two. Whenever you make a nobits item you limit zonemakers to make an item with better stats hence making the earlier version useless or you get the complaints described earlier. Also it gives zonemakers the ability to make quests to remove restrictions from items as a reward rather than upping stats.

Of course there can be a few exceptions, big quests maybe a few of the items in Tia and Baha but even there restricts would allow for future epic zones without the need to make the eq above what already exist, just different restricts for the most part.

I understand it would be a massive task going through all the eq already in the game but I'm sure many of us old zone makers would be willing to help.

**Comment by Uagr** [comment]
I don't like restrictions in general (mainly cause I see so many I feel are wrong !bits from realism or RP perspective, or too restrictive). But I do see where what you are recommending makes sense. However a big requirement is don't just limits based on a guess or whim, make it make sense... there is TONs of eq that has restrictions that makes no sense... on the restrictions, and actually look like the should be for the class that is restricted from using it. 
Can't tell you how many times i went "oh perfect for my (insert class/race here) oh... they cant wear it"..One example would be  the +9dr mage/bard only gloves ...it does brings back the old battlemage mentality tho :)
In general if done right I think race/class flags could be more easily implemented, but alignment flags should be used sparingly based on specific RP of the zone. Also look at things like no elf = no moon or drow , no dwarf = no duerg or dwarf,.

**Comment by shevarash** [comment]
I'm labeling this as a discussion since there isn't an actionable issue here to fix. 

As to the point of the issue, I agree that class or role based restrictions can be a very powerful tool to insure that there is a large enough variety in gear. We use those restrictions quite often, but it's true that unrestricted items to make it through from time to time.

**Comment by Dartan82** [comment]
_New zones are always followed by demands for better stats on the equipment and whining about how it's not better than the gear already in play._

This is only because the imms are trying to stop mudflation but instead just make bad gear nobody wants.   

If you want to break this dynamic of everyone thinking they can wait for Lilithelle to lead zones while we afk follow then create a reason to actually play the game.  It took 3 months for someone other than VB to even attempt one of the 5 "zones" in Unseelie and the result was "fuck this i'm not doing this again" or "lol this takes longer than Tiamat".

Here is my "i afk followed lili for bis and never need to touch the rest of the mud"
             :
<worn as a badge>    << the screaming hawk insignia of Keprum's army >>
<worn on head>       the mystical circlet of the coiled serpent
<worn on eyes>       a rune etched dragonscale of incarnadine hue
<worn in ear>        a teardrop earring of solid jade
<worn in ear>        a teardrop earring of solid jade
<worn on face>       a serrated red dragon mask
<worn around neck>   a thick titanium band of volance
<worn around neck>   a thick titanium band of volance
<worn on body>       a lightweight suit of linked mail body armor
<worn as quiver>     a quiver of stitched troll-skin
<worn about waist>   a sturdy belt lined with minotaur skulls
<worn on arms>       matte black drow chainmail sleeves
<worn around wrist>  a spiked astral metal wristguard
<worn around wrist>  a spiked astral metal wristguard
<worn on hands>      a pair of gauntlets wreathed in electricity (glowing)
<worn on finger>     a dragonhunter ring
<worn on finger>     a dragonhunter ring
<wielding twohanded> a golden-edged moonstone blade
<worn on legs>       a set of greaves made of jagged ice
<worn on feet>       the mystical boots of stability

**Comment by jokkmeister** [comment]
> I'm labeling this as a discussion since there isn't an actionable issue here to fix.
> 
> As to the point of the issue, I agree that class or role based restrictions can be a very powerful tool to insure that there is a large enough variety in gear. We use those restrictions quite often, but it's true that unrestricted items to make it through from time to time.

Well the restrictions are not enough Shev or else I wouldn't have needed to post this would I? I would rather argue that you remove restrictions on items rather than enforcing them. Most people don't like restrictions and I understand that but it's better to restrict than having the stupid issues we have now with noone being happy with new eq stats. New zones will always take timee to do the first times and if eq needs better and better stats well we would be limited to making harder and harder zones and quests rather than making more zones of about the same level with same statted eq made for different classes.

**Comment by shevarash** [comment]
I think you’re being a little vague here. Is there a specific item or zone whose lack of restrictions is bothering you?

**Comment by jokkmeister** [comment]
> I think you’re being a little vague here. Is there a specific item or zone whose lack of restrictions is bothering you?
> […](#)
> On Aug 7, 2020, at 3:38 PM, Ikhar ***@***.***> wrote: ﻿ I'm labeling this as a discussion since there isn't an actionable issue here to fix. As to the point of the issue, I agree that class or role based restrictions can be a very powerful tool to insure that there is a large enough variety in gear. We use those restrictions quite often, but it's true that unrestricted items to make it through from time to time. Well the restrictions are not enough Shev or else I wouldn't have needed to post this would I? I would rather argue that you remove restrictions on items rather than enforcing them. Most people don't like restrictions and I understand that but it's better to restrict than having the stupid issues we have now with noone being happy with new eq stats. New zones will always take timee to do the first times and if eq needs better and better stats well we would be limited to making harder and harder zones and quests rather than making more zones of about the same level with same statted eq made for different classes. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yeah I think you might misunderstand me a bit. I want harsher restrictions than warrior-only for example. More like warped broadsword, that items are restricted to subclasses. I mean linked suit and volance for example, there won't be such items for rogues so having a warrior-only flag is not really limiting them much. If they were say blk only or actually just warrior only (not including subclasses) then it would be better. There could be a quest for a ranger version of volance in unseelie and it would not break the game.

So less general restrictions and more restricts on subclasses. Baha was better but instead restrictions were removed there after complaints.

**Comment by shevarash** [comment]
Thank you for the feedback. We will consider this when designing new zones.
