### ISSUE TITLE
Solution to Greycloak bot camping problems

### ISSUE THREAD

**Issue by vitaladsr** [torilmud/issues#827]
Globally load the mobs across Faerun rather than specific in a small area like GC.

You can probably just change the 4 room exit numbers (from the distribution) into the overall toril distribution system.

**Comment by shevarash** [comment]
We'll consider that, but I'm reluctant to do so because the rares in GC are an important part of the zone's design.

**Comment by GeneralGormal** [comment]
The rares in Greycloak need to be made untrackable.  It's disheartening to see a single player running a track/kill script for years only to actually come to keys for enough time to turn on his Tiamat/Bahamut script and go afk again, denying the entire playerbase access to one of the most famous zones in the game.  Sadly, I doubt making things untrackable will be enough so you should really just make Swiftwind not charge in bags any longer because the impulse to hoard is just too strong for players to control their lesser impulses.

**Comment by GeneralGormal** [comment]
@shevarash
