### ISSUE TITLE
Phantom Heal

### ISSUE THREAD

**Issue by Nyyrazzilyss** [torilmud/issues#86]
Phantom heal restores 300hp if less them half maximum, then removes the 300hp after 2 minutes.

1) If the spell has been cast on someone, it doesn't show on status.
2) If cast on someone that has less then a maximum on 300hp at full hp, it will pkill them when it expires.
3) Getting killed doesn't remove the effect. You'll get killed by it expiring shortly after entering the portal

A couple things I would suggest:

Display phantom heal on status

The spell effect is a set value (300 hp). Perhaps change this to be level/skill related?

If phantom healing someone who has a maximum of 250 hp currently at 100hp, the spell effect only heals for 150hp. The penalty then when it expires should also be 150hp, not 300hp.

The hp loss when the spell expires should be reduced as a result of further healing having been
received. Perhaps if healed when already at maximum hp, any further healing reduces the penalty from when phantom heal expires. If it hits 0, the spell effect would just be removed completely despite having yet to expire.

**Comment by dnavarro** [comment]
Consider a significant overhaul to this spell

**Comment by Alurissi** [comment]
i'm with him on phantom heal, but with an additional issue, if my illusionist is decked out and has 900 hp, i get hurt, drop to 100 hp, phantom heal myself, i'm now at 350-400 hp depending upon spellfocus.  I'm still 500 hp away from max hp, and still under 50% of my total hitpoints, yet, as the spell is set to not be stackable, i can not cast again on myself until the first one drops.  Pretty much pointless, given that sure, the spell drop could result in death, but if i can't even get enough hp to continue fighting before the expiration time arrives, then no point continuing with the fight rather than just standing there and bandaging.

spell needs to be stackable, w/o changing duration, much like beautify

**Comment by shevarash** [comment]
This are all valid ideas, but the only actual bug I see here is that it's killing people after you've died. I will fix that part and file the rest as an enhancement idea.

**Comment by shevarash** [comment]
This will be addressed in an upcoming Illusionist class overhaul.
