### ISSUE TITLE
Ethereal Step doesn't work?

### ISSUE THREAD

**Issue by torkur** [torilmud/issues#925]
I can't get it to dim door to Ynndchiarhlizz, even when I'm 1 square away. I also made sure to get sorcery points in case.

You scan south...
Wayward House Inn (Shadowed)
Exits: -N -U
A gaping hole in the ground leads into darkness. (magic)
A small pile of coins.
[2] a jagged bone key lays discarded on the ground here.
Bubbinople  (Gnome) stands here.
A dapper noble is here socializing.
Zapzizel  (AFK) (Gnome) stands here.
Kayso  (Half-Orc) stands here.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A dapper noble is here socializing.
A dapper noble is here socializing.
Nyyrazzilyss  (AFK) (Illithid) sits resting.
Ynndchiarhlizz  (Illithid) sits resting.
Havorr Merendil stands behind the counter ready to serve.

You scan west...
Ghostwalk
Exits: -N -E -S -W
A ruby-throated humming bird hovers here feeding.

< 595h/703H 147v/150V |ar +|ec +|cb +|eb +|ps +|top +| >
< P: std > **est ynndchiarhlizz
Such paltry magics cannot hope to safely traverse such terrain!**

< 597h/703H 150v/150V |ar +|ec +|cb +|eb +|ps +|top +| >
< P: std >

**Comment by GeneralGormal** [comment]
You have to leave Silverymoon.  This is part of Silverymoon's (limited) mythal.  Lili made some concessions to gameplay because you shouldn't be allowed to portal at all without a ward token according to the lore.

Ghostwalk
Exits: -N -E -S -W
A chipmunk scampers along the ground here.

< 219h/219H 148v/150V P: std > You have successfully gained access to the Valkurian Blades association channel.

< 219h/219H 148v/150V P: std > cast 'dimension door' Ynndchiarhlizz
You start chanting...

< 219h/219H 148v/150V P: std > 
Casting: Dimension Door **

< 219h/219H 149v/150V P: std > 
Casting: Dimension Door *

< 219h/219H 150v/150V P: std > 
You complete your spell...
Such paltry magics cannot hope to safely traverse such terrain!
